prompt_zero_shot_expansion = "Perform query expansion on the given query. Enhance the query by adding additional, contextually relevant terms that could help retrieve documents lacking direct lexical overlap with the original query. Add synonyms or related terms to broaden its scope. Return only the expanded query."

prompt_few_shot_expansion = "Perform query expansion on the given query. Enhance the query by adding additional, contextually relevant terms that could help retrieve documents lacking direct lexical overlap with the original query. Add synonyms or related terms to broaden its scope. Return only the expanded query. Here are a few examples:Query: a deficiency of vitamin b12 increases blood levels of homocysteine Expanded: How does vitamin B12 deficiency or cobalamin deficiency lead to high homocysteine levels and increase the risk of heart disease or atherosclerosis. Query: Stopping Heart Disease in Childhood Expanded: Preventing heart disease in children, pediatric cardiovascular health, early intervention strategies Query: how can i get a cork out of a wine bottle without a corkscrew"

prompt_zero_shot_reduction = "Perform query reduction on the given query. Your task is to condense the query to its core meaning while removing any extraneous words. Try to retain as much meaning as possible from the original query even if it comes at a cost of smaller reductions. If the query is already brief, return it unchanged. Return only the reduced query."
   
prompt_few_shot_reduction = "Perform query reduction on the given query. Your task is to condense the query to its core meaning while removing any extraneous words. Try to retain as much meaning as possible from the original query even if it comes at a cost of smaller reductions. If the query is already brief, return it unchanged. Return only the reduced query. Here are a few examples: Query: a deficiency of vitamin b12 increases blood levels of homocysteine Reduced: Vitamin B12 deficiency increases homocysteine levels Query: Stopping Heart Disease in Childhood. Reduced: Preventing childhood heart disease Query: how can i get a cork out of a wine bottle without a corkscrew Reduced: How to remove a cork without a corkscrew"

prompt_zero_shot_keywords = "Extract keywords from the given query. Identify and list the core terms that capture the essence of the query. Return only the keywords as a list."

prompt_few_shot_keywords = "Extract keywords from the given query. Identify and list the core terms that capture the essence of the query. Return only the keywords as a list. Here are a few examples: Query: a deficiency of vitamin b12 increases blood levels of homocysteine Keywords: vitamin B12 deficiency, homocysteine Query: Stopping Heart Disease in Childhood Keywords: heart disease, childhood, prevention Query: how can i get a cork out of a wine bottle without a corkscrew Keywords: cork removal, wine bottle, alternative methods"
